"""empty message

Revision ID: 551736c21301
Revises: 
Create Date: 2020-11-30 12:56:56.410894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551736c21301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot')
    # ### end Alembic commands ###
